version: '3'

services:
  prenatal-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - prenatal_net2
    
  prenatal-api:
    restart: unless-stopped
    build: .
    environment:
      - ConnectionStrings:prenatal_db=Server=prenatal-sql,1433;Database=PrenatalDocker;User=sa;Password=QWElkj132!;ConnectRetryCount=0;MultipleActiveResultSets=true
    ports:
      - 54798:80
    networks:
      - prenatal_net2
    links:
      - prenatal-sql
    depends_on:
      - prenatal-sql
      
networks:
  prenatal_net1:
    driver: overlay
  prenatal_net2:
    driver: bridge
  prenatal_net3:
    driver: host
